import React, { useRef } from 'react';
import { AnalysisRecord } from '../contexts/HistoryContext';
import { useTheme } from '../contexts';
import { useToast } from './Toast';
import { useCopyToClipboard } from '../hooks/useCopyToClipboard';

interface ExportModalProps {
  record: AnalysisRecord;
  onClose: () => void;
}

const ExportModal: React.FC<ExportModalProps> = ({ record, onClose }) => {
  const { isModern, isDark } = useTheme();
  const { showToast } = useToast();
  const { copy } = useCopyToClipboard();
  const contentRef = useRef<HTMLDivElement>(null);

  const handleExportText = () => {
    const content = generateTextContent(record);
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `简历分析_${new Date(record.timestamp).toLocaleDateString('zh-CN').replace(/\//g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    showToast('导出成功', 'success');
  };

  const handleCopyAll = async () => {
    const content = generateTextContent(record);
    const ok = await copy(content);
    showToast(ok ? '已复制到剪贴板' : '复制失败', ok ? 'success' : 'error');
  };

  const generateTextContent = (record: AnalysisRecord) => {
    return `
=============================================
        简历分析报告
        ${new Date(record.timestamp).toLocaleString('zh-CN')}
=============================================

【关键词匹配度】${record.result.keywordMatch}%

【匹配分析】
${record.result.matchAnalysis}

【优势】
${record.result.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

【待提升】
${record.result.weaknesses.map((w, i) => `${i + 1}. ${w}`).join('\n')}

【定制化自我介绍】
${record.result.selfIntroduction}

=============================================
Generated by Resume Agent v3.0
=============================================
`;
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm" onClick={onClose} />
      <div className={`relative w-full max-w-lg rounded-3xl shadow-2xl ${
        isModern
          ? 'bg-white/95 backdrop-blur border border-slate-200/50'
          : 'bg-slate-900/95 backdrop-blur border border-slate-700/50'
      }`}>
        <div className="p-6">
          <h2 className={`text-xl font-bold mb-5 ${
            isModern
              ? 'bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-600'
              : 'bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-blue-400'
          }`}>
            📥 导出分析报告
          </h2>
          
          <div ref={contentRef} className={`p-5 rounded-2xl mb-5 max-h-64 overflow-y-auto ${
            isModern ? 'bg-slate-50' : 'bg-slate-800'
          }`}>
            <h3 className={`font-semibold mb-3 ${isModern ? 'text-slate-800' : 'text-slate-200'}`}>
              📊 简历分析报告
            </h3>
            <p className={`text-sm mb-2 ${isModern ? 'text-slate-600' : 'text-slate-400'}`}>
              匹配度: <span className={`font-bold ${
                record.result.keywordMatch >= 70
                  ? isModern ? 'text-emerald-600' : 'text-emerald-400'
                  : isModern ? 'text-amber-600' : 'text-amber-400'
              }`}>
                {record.result.keywordMatch}%
              </span>
            </p>
            <div className={`text-sm ${isModern ? 'text-slate-500' : 'text-slate-500'}`}>
              {record.result.strengths.length} 个优势 · {record.result.weaknesses.length} 个待提升
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={handleCopyAll}
              className={`flex-1 py-3.5 rounded-2xl font-semibold transition-all ${
                isModern
                  ? 'bg-slate-100 text-slate-700 hover:bg-slate-200 border border-slate-200'
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700'
              }`}
            >
              📋 复制全部
            </button>
            <button
              onClick={handleExportText}
              className={`flex-1 py-3.5 rounded-2xl font-semibold text-white shadow-lg hover:shadow-xl transition-all ${
                isModern
                  ? 'bg-gradient-to-r from-blue-500 to-indigo-600'
                  : 'bg-gradient-to-r from-purple-500 to-blue-600'
              }`}
            >
              📄 导出 TXT
            </button>
            <button
              onClick={onClose}
              className={`px-5 py-3.5 rounded-2xl font-semibold transition-all ${
                isModern
                  ? 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                  : 'bg-slate-800 text-slate-400 hover:bg-slate-700'
              }`}
            >
              关闭
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExportModal;
