import React, { useRef } from 'react';
import { AnalysisRecord } from '../contexts/HistoryContext';
import { useTheme } from '../contexts/ThemeContext';

interface ExportModalProps {
  record: AnalysisRecord;
  onClose: () => void;
}

const ExportModal: React.FC<ExportModalProps> = ({ record, onClose }) => {
  const { isDark } = useTheme();
  const contentRef = useRef<HTMLDivElement>(null);

  const handleExportText = () => {
    const content = generateTextContent(record);
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `简历分析_${new Date(record.timestamp).toLocaleDateString('zh-CN').replace(/\//g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleCopyAll = () => {
    const content = generateTextContent(record);
    navigator.clipboard.writeText(content);
    alert('已复制到剪贴板！');
  };

  const generateTextContent = (record: AnalysisRecord) => {
    return `
=============================================
        简历分析报告
        ${new Date(record.timestamp).toLocaleString('zh-CN')}
=============================================

【关键词匹配度】${record.result.keywordMatch}%

【匹配分析】
${record.result.matchAnalysis}

【优势】
${record.result.strengths.map((s, i) => `${i + 1}. ${s}`).join('\n')}

【待提升】
${record.result.weaknesses.map((w, i) => `${i + 1}. ${w}`).join('\n')}

【定制化自我介绍】
${record.result.selfIntroduction}

=============================================
Generated by Resume Agent
=============================================
`;
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/50" onClick={onClose} />
      <div className={`relative w-full max-w-lg rounded-2xl shadow-2xl ${
        isDark ? 'bg-gray-800' : 'bg-white'
      }`}>
        <div className="p-6">
          <h2 className={`text-xl font-bold mb-4 ${isDark ? 'text-white' : 'text-gray-800'}`}>
            📥 导出分析报告
          </h2>
          
          {/* 预览内容 */}
          <div ref={contentRef} className={`p-4 rounded-lg mb-4 max-h-64 overflow-y-auto ${
            isDark ? 'bg-gray-700' : 'bg-gray-50'
          }`}>
            <h3 className={`font-medium mb-2 ${isDark ? 'text-gray-200' : 'text-gray-700'}`}>
              📊 简历分析报告
            </h3>
            <p className={`text-sm mb-2 ${isDark ? 'text-gray-300' : 'text-gray-600'}`}>
              匹配度: <span className={record.result.keywordMatch >= 70 ? 'text-green-500 font-bold' : 'text-yellow-500 font-bold'}>
                {record.result.keywordMatch}%
              </span>
            </p>
            <div className="text-sm text-gray-500">
              {record.result.strengths.length} 个优势 · {record.result.weaknesses.length} 个待提升
            </div>
          </div>

          {/* 按钮组 */}
          <div className="flex gap-3">
            <button
              onClick={handleCopyAll}
              className={`flex-1 py-3 rounded-xl font-medium transition-colors ${
                isDark
                  ? 'bg-gray-700 text-gray-200 hover:bg-gray-600'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              📋 复制全部
            </button>
            <button
              onClick={handleExportText}
              className="flex-1 py-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-medium transition-colors"
            >
              📄 导出 TXT
            </button>
            <button
              onClick={onClose}
              className={`px-4 py-3 rounded-xl font-medium ${
                isDark ? 'bg-gray-700 text-gray-300' : 'bg-gray-100 text-gray-600'
              }`}
            >
              关闭
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ExportModal;